# Generated by Django 4.0.5 on 2022-06-06 15:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='certificate image')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='work image')),
            ],
            options={
                'verbose_name': 'Work Image',
                'verbose_name_plural': 'Work Images',
            },
        ),
    ]
